import type { Metadata } from "next";
import "./globals.css";
import React from 'react';
import CssBaseline from '@mui/joy/CssBaseline';
import { CssVarsProvider } from '@mui/joy/styles';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <CssVarsProvider defaultMode="dark">
        <CssBaseline />
        {children}
      </CssVarsProvider>
      </body>
    </html>
  );
}
